language: android
jdk: oraclejdk8
sudo: false
addons:
  apt:
    packages:
    - lynx
android:
  components:
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
    - extra-android-m2repository
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
before_install: chmod +x gradle/buildWithTravis.sh
script: gradle/buildWithTravis.sh
env:
  global:
  - secure: W0ZmbTQvGqWf4hb/lMfKAGfeotCmufBiYoEFL7Vszc8Q3cbNL7N3zqOy1dRwWcL2/lnDSkgldDoOR1H1eCcWwfgrKC0N36ZXGQ+MX8Psbu4dLdaNF9Fdkzf34s7w6vC/ZHHH3Mf6FVMdRr75WP71htIcHzfeN684ZJpuf00zE0tu32Eofl3RlZUcMJ1WqqNMjrmvcJdjQpxQzCcgLuW5xcIeHenk3I9X9lAl6r0gK9s+tGbKzC496vvO++9ikKjkHRJGZJxmgKfnFYK8UeXCt0uBJKK5PvoQq6jcpDIXkRBxrvuxisqRczrOyNQ7uXLIs5/kkZwqzmrZkomorE3g1OJTK5ovSIffdg/ffdZFcegNOsNvsxMUD/VvokUIfKBvSo4KHTrdntPuRd41dIBEIQqjfvX54lQJ5yXqESjfIMAxqn4kVBR/REojDRq4+Pj5tl+jBKfFoDb9sZ2cehBhiMKi5iXpoynUxP+/sQc++fL3vMv3Npwp3Y7yf3QCiq8CcSWrJwfcWWkz5QAUJkn9HXB8K9YWmFspIamFzkbKt4/StDdfevai40V+VBRSBeNO11hknz+breD6uAhqh7VzK/ENLhuoAHQxKFu/g7xrj5vT7qdLgxCO2jxCuZJs4wULRrLY0zl8fKYlJXJhLLNWLJcFa+FQ6ZowGV23mmp5N3Q=
  - secure: e150LK1NZHIZfvyg0/uD8c9TT7S/R8vFlpZd9nolCWH1k4kHa9sxdQigNXz3UT9yE35DzBri/mo/t/6KVv/LgbnVZhMTsJEcmYbgXMynifgVNmFFdIsV5IHgL5h5ltglhZclJDlGrMEzLKKGJHUJTNgBHwAtuDhr62WfSDAUdkSZXFh9+3Q9jCmbQozQyl/fE/dfiekNOCIFAAaLwzYtyJ/lHxQt+2KufqyG1CWCXyer6Br2OmDuu5gRmkW54T7iJ22ofmn/iB4ec1WeFGvMQji49BnK1kYFhq+ZA24HAU7VctDWRtHQeEynC9XX1iEljzjha5unvYUkLrbBdtCx9AGmMC4PBr9s6t5XUVrNNq1fPsilK/vNvFOuDl5XJ7b/ZXoplh2ZoREPIiHAH/IfZy97DXdM+3FPvc/jAza6VBK7QSb/iArSwsCFuB+xE32KUuANnbw1j7W6H4gG2LEUT2+UPfp4ZgwdnvH9IM7sD/o8B4OhtC25fV7R24HIaUpl1PNQyPT+ryjpNZ1g2Z3vpeMqgJcgicMRVuVK/ljkiTSnhLWTjuVRa3aIqcsNLXzmweZaaYM12r70Y6WtEermfbnCVIjJ0UquGbv6d43q5dJBGPr3K9Oa9JAB6zDHFF8kkxlicazwjzPR/TZ2AFxhYsyyRNg8v+Utudb+TCLNHMU=
